server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.122.155.110:3306/petshop_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456  # 确保与docker-compose.yml中的MYSQL_ROOT_PASSWORD一致

  data:
    redis:
      host: 47.122.155.110  # 使用公网IP
      port: 6379
      password: 123456  # 确保与docker-compose.yml中的requirepass一致

    mongodb:
      uri: mongodb://root:123456@47.122.155.110:27017/petshop_geo?authSource=admin&connectTimeoutMS=5000&socketTimeoutMS=5000

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/
  ai:
    openai:
      # 1. 您的硅基流动 API Key (保持不变)
      api-key: sk-xdsrciiskbkjlsoezabveiucbbfxwwbkzzwtihavviwhwrpd

      # 2. [核心修正] 将base-url的末尾加上 /v1
      base-url: https://api.siliconflow.cn

      chat:
        options:
          # 3. 您想使用的模型 (保持不变)
          model: deepseek-ai/DeepSeek-R1-0528-Qwen3-8B # 您可以换成其他模型如 "Qwen/Qwen2-7B-Instruct"

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml


file:
  upload-dir: ./uploads/

# 配置springdoc-openapi，用于文档化和访问API
springdoc:
  # 配置Swagger UI的访问路径和排序方式
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI的访问路径
    tags-sorter: alpha      # 按字母顺序排序标签
    operations-sorter: alpha  # 按字母顺序排序操作
  # 配置API文档的访问路径
  api-docs:
    path: /v3/api-docs  # API文档的访问路径
  # 配置API分组，用于组织和管理API
  group-configs:
    - group: 'default'   # API分组名称
      paths-to-match: '/**'  # 匹配所有路径
      packages-to-scan: com.example.petshopbackend.controller  # 扫描的包，用于自动发现API

jwt:
  secret: NKcdTFaPfQ4kr3pVbT3zz5LnKlJMm7PIKR3cbNGBakU=
  expire: 3600000