server:
  port: 8080
  error:
    include-message: always

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: static/**
  jmx:
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petshop_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
    mongodb:
      uri: mongodb://root:123456@localhost:27017/petshop_geo?authSource=admin
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

jwt:
  secret: NKcdTFaPfQ4kr3pVbT3zz5LnKlJMm7PIKR3cbNGBakU=
  expire: 3600000
